stage:
- build
- deploy
- post

build:
- maven:
    goal: clean install
    options: -Dmaven.test.skip=true
- docker:
  - docker
  - version

deploy:
- kubectl: kubectl get all
- golang: go version

#agent: [maven, docker, kubectl]
agent:
  profile: [maven, docker, kubectl]
  containers:
  - name: golang
    image: golang:1.8.0
    ttyEnabled: true
    command: cat
  volumes:
  - persistentVolumeClaim:
      claimName: slave-workspace
      mountPath: /root/.m2/repository
      readOnly: false

#type: container
