type: container

build:
- maven:
    goal: clean install
    options: -Dmaven.test.skip=true
- docker:
  - docker
  - version

#deploy:
#- k8s: k8s/*.yaml

agent:
  containers:
  - name: kubectl
    image: 'lachlanevenson/k8s-kubectl'
    ttyEnabled: true
    command: cat
  volumes:
  - persistentVolumeClaim:
      claimName: slave-workspace
      mountPath: /root/.m2/repository
      readOnly: false

stage:
- build
- deploy
