build:
- maven: clean install
- docker: web/Dockerfile

deploy:
- k8s: k8s/*.yaml

agent:
  containers:
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    ttyEnabled: true
    command: cat
  - name: maven3.3
    image: maven:3.3.9-jdk-8-alpine
    ttyEnabled: true
    command: cat

stage:
- build
- deploy
